version: '3.9'

services:

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper\
  
  app:
    build:
      context: .           
      dockerfile: dockerfile
    depends_on:
      - kafka
    command: python scheduler.py
    env_file:
      - .env               


  tiktok_gatherer:
    build:
      context: ./gatherers/tiktok
      dockerfile: Dockerfile
    depends_on:
      - kafka
    command: python tiktok_gatherer.py
    env_file:
      - ./gatherers/tiktok/.env

  mongo_writer:
    build:
      context: ./consumers/mongo_writer
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - mongo
    command: python mongo_writer.py
    env_file:
      - ../.env
    
